/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f8fafc",
        "on-background": "#0f172a",
        "surface": "#ffffff",
        "surface-dim": "#f1f5f9",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#ffffff",
        "surface-container-highest": "#e2e8f0",
        "on-surface": "#0f172a",
        "on-surface-variant": "#64748b",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#ffffff",
        "outline": "#e2e8f0",
        "outline-variant": "#cbd5e1",
        "primary": "#2563eb",
        "on-primary": "#ffffff",
        "primary-container": "#eff6ff",
        "on-primary-container": "#1e40af",
        "secondary": "#64748b",
        "on-secondary": "#ffffff",
        "studio-dark": "#0f172a",
        "studio-blue": "#2563eb",
        "studio-indigo": "#6366f1",
        "studio-teal": "#0d9488",
      },
      boxShadow: {
        '3d-sm': '0 4px 14px 0 rgba(0, 0, 0, 0.04), 0 1px 2px 0 rgba(0, 0, 0, 0.02)',
        '3d-card': '0 20px 50px rgba(0, 0, 0, 0.04), 0 1px 4px rgba(0, 0, 0, 0.02)',
        '3d-hover': '0 25px 50px -12px rgba(37, 99, 235, 0.15), 0 8px 16px -4px rgba(0, 0, 0, 0.04)',
        '3d-floating': '0 30px 60px -12px rgba(15, 23, 42, 0.12), 0 18px 36px -18px rgba(0, 0, 0, 0.08)',
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.06)',
      },
      fontFamily: {
        serif: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "12px",
        sm: "6px",
        md: "10px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
        full: "9999px",
      }
    },
  },
  plugins: [],
}
